
package co.gov.anm.proxy;

import co.gov.anm.xmlns.appopt.aoptcommon_v1.MsgHdrRq;
import co.gov.anm.xmlns.appopt.aoptcommon_v1.MsgHdrRs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.anm.xmlns.appopt.reportesappsvc.resultadoscomparaciones_v1.ResultadosComparacionesRqType;
import co.gov.anm.xmlns.appopt.reportesappsvc.resultadoscomparaciones_v1.ResultadosComparacionesRsType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "ReportesResultadosComparacionesAppSvcPort",
            targetNamespace = "http://xmlns.anm.gov.co/AppSvc/ResultadosComparaciones_V1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ co.gov.anm.xmlns.appopt.aoptcommon_v1.ObjectFactory.class,
              co.gov.anm.xmlns.appopt.reportesappsvc.resultadoscomparaciones_v1.ObjectFactory.class,
              co.gov.anm.xmlns.eo.status_v1.ObjectFactory.class
    })
public interface ReportesResultadosComparacionesAppSvcPort {


    /**
     *
     * @param resultadosComparacionesRq
     * @return
     *     returns co.gov.anm.xmlns.appopt.reportesappsvc.resultadoscomparaciones_v1.ResultadosComparacionesRsType
     * @throws SystemFault
     */
    @WebMethod(operationName = "ResultadosComparaciones",
               action = "http://xmlns.anm.gov.co/ApplicationService/ReportesAppSvc_V1.0/ResultadosComparaciones")
    @WebResult(name = "ResultadosComparacionesRs",
               targetNamespace = "http://xmlns.anm.gov.co/appopt/ReportesAppSvc/ResultadosComparaciones_V1.0",
               partName = "ResultadosComparacionesRs")
    public ResultadosComparacionesRsType resultadosComparaciones(@WebParam(name = "ResultadosComparacionesRq",
                                                                           targetNamespace =
                                                                           "http://xmlns.anm.gov.co/appopt/ReportesAppSvc/ResultadosComparaciones_V1.0",
                                                                           partName = "ResultadosComparacionesRq")
                                                                 ResultadosComparacionesRqType resultadosComparacionesRq) throws SystemFault;

    public ResultadosComparacionesRsType resultadosComparaciones(ResultadosComparacionesRqType resultadosComparacionesRq,
                                                                 MsgHdrRq msgHdrRq, MsgHdrRs msgHdrRs);
}
