
package co.gov.anm.proxy;

import co.gov.anm.xmlns.appopt.aoptcommon_v1.MsgHdrRq;
import co.gov.anm.xmlns.appopt.aoptcommon_v1.MsgHdrRs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.anm.xmlns.appopt.reportesappsvc.consultarvencimientocontractual_v1.ConsultarVencimientoContractualRqType;
import co.gov.anm.xmlns.appopt.reportesappsvc.consultarvencimientocontractual_v1.ConsultarVencimientoContractualRsType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultarVencimientoContractualAppSvcPort",
            targetNamespace = "http://xmlns.anm.gov.co/AppSvc/ConsultarVencimientoContractual_V1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ co.gov.anm.xmlns.appopt.aoptcommon_v1.ObjectFactory.class,
              co.gov.anm.xmlns.appopt.reportesappsvc.consultarvencimientocontractual_v1.ObjectFactory.class,
              co.gov.anm.xmlns.eo.status_v1.ObjectFactory.class
    })
public interface ConsultarVencimientoContractualAppSvcPort {


    /**
     *
     * @param consultarVencimientoContractualRq
     * @return
     *     returns co.gov.anm.xmlns.appopt.reportesappsvc.consultarvencimientocontractual_v1.ConsultarVencimientoContractualRsType
     * @throws SystemFault
     */
    @WebMethod(operationName = "ConsultarVencimientoContractual",
               action =
               "http://xmlns.anm.gov.co/ApplicationService/ReportesAppSvc_V1.0/ConsultarVencimientoContractual")
    @WebResult(name = "ConsultarVencimientoContractualRs",
               targetNamespace = "http://xmlns.anm.gov.co/appopt/ReportesAppSvc/ConsultarVencimientoContractual_V1.0",
               partName = "ConsultarVencimientoContractualRs")
    public ConsultarVencimientoContractualRsType consultarVencimientoContractual(@WebParam(name =
                                                                                           "ConsultarVencimientoContractualRq",
                                                                                           targetNamespace =
                                                                                           "http://xmlns.anm.gov.co/appopt/ReportesAppSvc/ConsultarVencimientoContractual_V1.0",
                                                                                           partName =
                                                                                           "ConsultarVencimientoContractualRq")
                                                                                 ConsultarVencimientoContractualRqType consultarVencimientoContractualRq) throws SystemFault;

    public void consultarVencimientoContractual(ConsultarVencimientoContractualRqType consultarVencimientoContractualRq,
                                                MsgHdrRq msgHdrRq, MsgHdrRs msgHdrRs);
}
