package co.gov.anm.proxy;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.3.0.0914
public class ReportesAppSvcBindingSOAP11QSPortClient {
    public static void main(String[] args) {
        ReportesAppSvcBindingSOAP11QSService reportesAppSvcBindingSOAP11QSService =
            new ReportesAppSvcBindingSOAP11QSService();
        ConsultarVencimientoContractualAppSvcPort consultarVencimientoContractualAppSvcPort =
            reportesAppSvcBindingSOAP11QSService.getReportesAppSvcBindingSOAP11QSPort();
        // Add your code to call the desired methods.


    }
}
