
package co.gov.anm.proxy;

import javax.xml.ws.WebFault;

import co.gov.anm.xmlns.eo.status_v1.Status;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebFault(name = "SystemFault", targetNamespace = "http://xmlns.anm.gov.co/eo/Status_V1.0")
public class SystemFault extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     *
     */
    private Status faultInfo;

    /**
     *
     * @param faultInfo
     * @param message
     */
    public SystemFault(String message, Status faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SystemFault(String message, Status faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @return
     *     returns fault bean: co.gov.anm.xmlns.eo.status_v1.Status
     */
    public Status getFaultInfo() {
        return faultInfo;
    }

}
