
package co.gov.anm.xmlns.appsvc.consultartitulos_v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.anm.xmlns.appopt.alertasappsvc.consultartitulos_v1.ConsultarTitulosRqType;
import co.gov.anm.xmlns.appopt.alertasappsvc.consultartitulos_v1.ConsultarTitulosRsType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "AlertasConsultarTitulosAppSvcPort",
            targetNamespace = "http://xmlns.anm.gov.co/AppSvc/ConsultarTitulos_V1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ co.gov.anm.xmlns.appopt.alertasappsvc.consultartitulos_v1.ObjectFactory.class,
              co.gov.anm.xmlns.appopt.aoptcommon_v1.ObjectFactory.class,
              co.gov.anm.xmlns.eo.status_v1.ObjectFactory.class
    })
public interface AlertasConsultarTitulosAppSvcPort {


    /**
     *
     * @param consultarTitulosRq
     * @return
     *     returns co.gov.anm.xmlns.appopt.alertasappsvc.consultartitulos_v1.ConsultarTitulosRsType
     * @throws SystemFault
     */
    @WebMethod(operationName = "ConsultarTitulos",
               action = "http://xmlns.anm.gov.co/ApplicationService/AlertasAppSvc_V1.0/ConsultarTitulos")
    @WebResult(name = "ConsultarTitulosRs",
               targetNamespace = "http://xmlns.anm.gov.co/appopt/AlertasAppSvc/ConsultarTitulos_V1.0",
               partName = "ConsultarTitulosRs")
    public ConsultarTitulosRsType consultarTitulos(@WebParam(name = "ConsultarTitulosRq",
                                                             targetNamespace =
                                                             "http://xmlns.anm.gov.co/appopt/AlertasAppSvc/ConsultarTitulos_V1.0",
                                                             partName = "ConsultarTitulosRq")
                                                   ConsultarTitulosRqType consultarTitulosRq) throws SystemFault;

}
