
package co.gov.anm.proxy;

import co.gov.anm.xmlns.appopt.aoptcommon_v1.MsgHdrRq;
import co.gov.anm.xmlns.appopt.aoptcommon_v1.MsgHdrRs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.anm.xmlns.appopt.reportesappsvc.consultarestadorequerimiento_v1.ConsultarEstadoRequerimientoRqType;
import co.gov.anm.xmlns.appopt.reportesappsvc.consultarestadorequerimiento_v1.ConsultarEstadoRequerimientoRsType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "ReportesConsultarEstadoRequerimientoAppSvcPort",
            targetNamespace = "http://xmlns.anm.gov.co/AppSvc/ConsultarEstadoRequerimiento_V1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ co.gov.anm.xmlns.appopt.aoptcommon_v1.ObjectFactory.class,
              co.gov.anm.xmlns.appopt.reportesappsvc.consultarestadorequerimiento_v1.ObjectFactory.class,
              co.gov.anm.xmlns.eo.status_v1.ObjectFactory.class
    })
public interface ReportesConsultarEstadoRequerimientoAppSvcPort {


    /**
     *
     * @param consultarEstadoRequerimientoRq
     * @return
     *     returns co.gov.anm.xmlns.appopt.reportesappsvc.consultarestadorequerimiento_v1.ConsultarEstadoRequerimientoRsType
     * @throws SystemFault
     */
    @WebMethod(operationName = "ConsultarEstadoRequerimiento",
               action = "http://xmlns.anm.gov.co/ApplicationService/ReportesAppSvc_V1.0/ConsultarEstadoRequerimiento")
    @WebResult(name = "ConsultarEstadoRequerimientoRs",
               targetNamespace = "http://xmlns.anm.gov.co/appopt/ReportesAppSvc/ConsultarEstadoRequerimiento_V1.0",
               partName = "ConsultarEstadoRequerimientoRs")
    public ConsultarEstadoRequerimientoRsType consultarEstadoRequerimiento(@WebParam(name =
                                                                                     "ConsultarEstadoRequerimientoRq",
                                                                                     targetNamespace =
                                                                                     "http://xmlns.anm.gov.co/appopt/ReportesAppSvc/ConsultarEstadoRequerimiento_V1.0",
                                                                                     partName =
                                                                                     "ConsultarEstadoRequerimientoRq")
                                                                           ConsultarEstadoRequerimientoRqType consultarEstadoRequerimientoRq) throws SystemFault;

    public ConsultarEstadoRequerimientoRsType consultarEstadoRequerimiento(ConsultarEstadoRequerimientoRqType consultarEstadoRequerimientoRq,
                                                                           MsgHdrRq msgHdrRq, MsgHdrRs msgHdrRs);
}
