
package co.gov.anm.xmlns.appsvc.consultarproyecto_v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.anm.xmlns.appopt.alertasappsvc.consultarproyecto_v1.ConsultarProyectoRqType;
import co.gov.anm.xmlns.appopt.alertasappsvc.consultarproyecto_v1.ConsultarProyectoRsType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "AlertasAppSvcPort", targetNamespace = "http://xmlns.anm.gov.co/AppSvc/ConsultarProyecto_V1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ co.gov.anm.xmlns.appopt.alertasappsvc.consultarproyecto_v1.ObjectFactory.class,
              co.gov.anm.xmlns.appopt.aoptcommon_v1.ObjectFactory.class,
              co.gov.anm.xmlns.eo.status_v1.ObjectFactory.class
    })
public interface AlertasAppSvcPort {


    /**
     *
     * @param consultarProyectoRq
     * @return
     *     returns co.gov.anm.xmlns.appopt.alertasappsvc.consultarproyecto_v1.ConsultarProyectoRsType
     * @throws SystemFault
     */
    @WebMethod(operationName = "ConsultarProyecto",
               action = "http://xmlns.anm.gov.co/ApplicationService/AlertasAppSvc_V1.0/ConsultarProyecto")
    @WebResult(name = "ConsultarProyectoRs",
               targetNamespace = "http://xmlns.anm.gov.co/appopt/AlertasAppSvc/ConsultarProyecto_V1.0",
               partName = "ConsultarProyectoRs")
    public ConsultarProyectoRsType consultarProyecto(@WebParam(name = "ConsultarProyectoRq",
                                                               targetNamespace =
                                                               "http://xmlns.anm.gov.co/appopt/AlertasAppSvc/ConsultarProyecto_V1.0",
                                                               partName = "ConsultarProyectoRq")
                                                     ConsultarProyectoRqType consultarProyectoRq) throws SystemFault;

}
