package co.gov.anm.proxy;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.3.0.0914
public class ListaValoresAppSvcBindingSOAP11QSPortClient {
    public static void main(String[] args) {
        ListaValoresAppSvcBindingSOAP11QSService listaValoresAppSvcBindingSOAP11QSService =
            new ListaValoresAppSvcBindingSOAP11QSService();
        ListaValoresAppSvcPort listaValoresAppSvcPort =
            listaValoresAppSvcBindingSOAP11QSService.getListaValoresAppSvcBindingSOAP11QSPort();
        // Add your code to call the desired methods.


    }
}
