
package co.gov.anm.proxy;

import co.gov.anm.xmlns.appopt.aoptcommon_v1.MsgHdrRq;
import co.gov.anm.xmlns.appopt.aoptcommon_v1.MsgHdrRs;
import co.gov.anm.xmlns.appopt.listavaloresappsvc.consultarlistavalores_v1.ConsultarListaValoresRqType;
import co.gov.anm.xmlns.appopt.listavaloresappsvc.consultarlistavalores_v1.ConsultarListaValoresRsType;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "ListaValoresAppSvcPort",
            targetNamespace = "http://xmlns.anm.gov.co/AppSvc/ConsultarListaValores_V1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED)
@XmlSeeAlso({ co.gov.anm.xmlns.appopt.aoptcommon_v1.ObjectFactory.class,
              co.gov.anm.xmlns.appopt.listavaloresappsvc.consultarlistavalores_v1.ObjectFactory.class,
              co.gov.anm.xmlns.eo.status_v1.ObjectFactory.class
    })
public interface ListaValoresAppSvcPort {


    /**
     *
     * @param consultarListaValoresRq
     * @return
     *     returns co.gov.anm.xmlns.appopt.listavaloresappsvc.consultarlistavalores_v1.ConsultarListaValoresRsType
     * @throws SystemFault
     */
    @WebMethod(operationName = "ConsultarListaValores",
               action = "http://xmlns.anm.gov.co/ApplicationService/ListaValoresAppSvc_V1.0/ConsultarListaValores")
    @WebResult(name = "ConsultarListaValoresRs",
               targetNamespace = "http://xmlns.anm.gov.co/appopt/ListaValoresAppSvc/ConsultarListaValores_V1.0",
               partName = "ConsultarListaValoresRs")
    public ConsultarListaValoresRsType consultarListaValores(@WebParam(name = "ConsultarListaValoresRq",
                                                                       targetNamespace =
                                                                       "http://xmlns.anm.gov.co/appopt/ListaValoresAppSvc/ConsultarListaValores_V1.0",
                                                                       partName = "ConsultarListaValoresRq")
                                                             ConsultarListaValoresRqType consultarListaValoresRq) throws SystemFault;

    public ConsultarListaValoresRsType consultarListaValores(ConsultarListaValoresRqType consultarListaValoresRq,
                                                             MsgHdrRq msgHdrRq, MsgHdrRs msgHdrRs);
}
