
package co.gov.anm.proxy;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ListaValoresAppSvcBindingSOAP11QSService",
                  targetNamespace = "http://xmlns.anm.gov.co/AppSvc/ConsultarListaValores_V1.0",
                  wsdlLocation =
                  "http://192.168.1.24:8011/ListaValoresRS/ConsultarListaValores?WSDL#%7Bhttp%3A%2F%2Fxmlns.anm.gov.co%2FAppSvc%2FConsultarListaValores_V1.0%7DListaValoresAppSvcBindingSOAP11QSService")
public class ListaValoresAppSvcBindingSOAP11QSService extends Service {

    private final static URL LISTAVALORESAPPSVCBINDINGSOAP11QSSERVICE_WSDL_LOCATION;
    private final static WebServiceException LISTAVALORESAPPSVCBINDINGSOAP11QSSERVICE_EXCEPTION;
    private final static QName LISTAVALORESAPPSVCBINDINGSOAP11QSSERVICE_QNAME =
        new QName("http://xmlns.anm.gov.co/AppSvc/ConsultarListaValores_V1.0",
                  "ListaValoresAppSvcBindingSOAP11QSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://192.168.1.24:8011/ListaValoresRS/ConsultarListaValores?WSDL#%7Bhttp%3A%2F%2Fxmlns.anm.gov.co%2FAppSvc%2FConsultarListaValores_V1.0%7DListaValoresAppSvcBindingSOAP11QSService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LISTAVALORESAPPSVCBINDINGSOAP11QSSERVICE_WSDL_LOCATION = url;
        LISTAVALORESAPPSVCBINDINGSOAP11QSSERVICE_EXCEPTION = e;
    }

    public ListaValoresAppSvcBindingSOAP11QSService() {
        super(__getWsdlLocation(), LISTAVALORESAPPSVCBINDINGSOAP11QSSERVICE_QNAME);
    }

    public ListaValoresAppSvcBindingSOAP11QSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LISTAVALORESAPPSVCBINDINGSOAP11QSSERVICE_QNAME, features);
    }

    public ListaValoresAppSvcBindingSOAP11QSService(URL wsdlLocation) {
        super(wsdlLocation, LISTAVALORESAPPSVCBINDINGSOAP11QSSERVICE_QNAME);
    }

    public ListaValoresAppSvcBindingSOAP11QSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LISTAVALORESAPPSVCBINDINGSOAP11QSSERVICE_QNAME, features);
    }

    public ListaValoresAppSvcBindingSOAP11QSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ListaValoresAppSvcBindingSOAP11QSService(URL wsdlLocation, QName serviceName,
                                                    WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ListaValoresAppSvcPort
     */
    @WebEndpoint(name = "ListaValoresAppSvcBindingSOAP11QSPort")
    public ListaValoresAppSvcPort getListaValoresAppSvcBindingSOAP11QSPort() {
        return super.getPort(new QName("http://xmlns.anm.gov.co/AppSvc/ConsultarListaValores_V1.0",
                                       "ListaValoresAppSvcBindingSOAP11QSPort"), ListaValoresAppSvcPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ListaValoresAppSvcPort
     */
    @WebEndpoint(name = "ListaValoresAppSvcBindingSOAP11QSPort")
    public ListaValoresAppSvcPort getListaValoresAppSvcBindingSOAP11QSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.anm.gov.co/AppSvc/ConsultarListaValores_V1.0",
                                       "ListaValoresAppSvcBindingSOAP11QSPort"), ListaValoresAppSvcPort.class,
                             features);
    }

    private static URL __getWsdlLocation() {
        if (LISTAVALORESAPPSVCBINDINGSOAP11QSSERVICE_EXCEPTION != null) {
            throw LISTAVALORESAPPSVCBINDINGSOAP11QSSERVICE_EXCEPTION;
        }
        return LISTAVALORESAPPSVCBINDINGSOAP11QSSERVICE_WSDL_LOCATION;
    }

}
