
package co.gov.anm.proxy;

import co.gov.anm.xmlns.appopt.aoptcommon_v1.MsgHdrRq;
import co.gov.anm.xmlns.appopt.aoptcommon_v1.MsgHdrRs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.anm.xmlns.appopt.alertasappsvc.consultartitulo_v1.ConsultarTituloRqType;
import co.gov.anm.xmlns.appopt.alertasappsvc.consultartitulo_v1.ConsultarTituloRsType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "AlertasConsultarTituloAppSvcPort",
            targetNamespace = "http://xmlns.anm.gov.co/AppSvc/ConsultarTitulo_V1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ co.gov.anm.xmlns.appopt.alertasappsvc.consultartitulo_v1.ObjectFactory.class,
              co.gov.anm.xmlns.appopt.aoptcommon_v1.ObjectFactory.class,
              co.gov.anm.xmlns.eo.status_v1.ObjectFactory.class
    })
public interface AlertasConsultarTituloAppSvcPort {


    /**
     *
     * @param consultarTituloRq
     * @return
     *     returns co.gov.anm.xmlns.appopt.alertasappsvc.consultartitulo_v1.ConsultarTituloRsType
     * @throws SystemFault
     */
    @WebMethod(operationName = "ConsultarTitulo",
               action = "http://xmlns.anm.gov.co/ApplicationService/AlertasAppSvc_V1.0/ConsultarTitulo")
    @WebResult(name = "ConsultarTituloRs",
               targetNamespace = "http://xmlns.anm.gov.co/appopt/AlertasAppSvc/ConsultarTitulo_V1.0",
               partName = "ConsultarTituloRs")
    public ConsultarTituloRsType consultarTitulo(@WebParam(name = "ConsultarTituloRq",
                                                           targetNamespace =
                                                           "http://xmlns.anm.gov.co/appopt/AlertasAppSvc/ConsultarTitulo_V1.0",
                                                           partName = "ConsultarTituloRq")
                                                 ConsultarTituloRqType consultarTituloRq) throws SystemFault;

    public ConsultarTituloRsType consultarTitulo(ConsultarTituloRqType consultarTituloRq, MsgHdrRq msgHdrRq,
                                                 MsgHdrRs msgHdrRs);
}
